spring:
  application:
    name: hello-spring-cloud-eureka
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8084

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:  #通过 eureka.client.registerWithEureka:false 和 fetchRegistry:false 来表明自己是一个 Eureka Server
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl: #eureka地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/